@rem set HADOOP_COMMON_HOME=C:\hd2dep\hadoop-common-2.2.1-SNAPSHOT
set HADOOP_CONF_DIR=C:\hd2dep\conf
@rem set HADOOP_CORE_HOME=C:\hd2dep\hadoop-common-2.2.1-SNAPSHOT
@rem set HADOOP_HDFS_HOME=C:\hd2dep\hadoop-hdfs-2.2.1-SNAPSHOT
@rem set HADOOP_MAPRED_HOME=C:\hd2dep\hadoop-mapreduce-2.2.1-SNAPSHOT
@rem set HADOOP_PREFIX=C:\hd2dep\hadoop-common-2.2.1-SNAPSHOT
@rem set YARN_HOME=C:\hd2dep\hadoop-yarn-project-2.2.1-SNAPSHOT
set YARN_CONF_DIR=%HADOOP_CONF_DIR%
set HADOOP_USER_CLASSPATH_FIRST=true
set HADOOP_CLASSPATH=C:\hd2\hadoop-hdfs-project\hadoop-hdfs\target\classes
